### ISSUE TITLE
provider.Client.generateContentStream does not compile

### ISSUE THREAD

**Issue by mrusme** [lightpanda-io/zenai#14]
Calling `zenai.provider.Client.generateContentStream` fails to compile on Zig 0.16.0 at zenai `be5d2e7`. The function is generic, nothing in the repository instantiates it, and Zig only analyzes a generic function body at instantiation, so `zig build test` passes and the errors only appear when actually tyring to use it.

You can reproduce it like this:

```zig
.{
    .name = .repro,
    .version = "0.0.0",
    .fingerprint = 0xdd3d4c6eda0c643a,
    .minimum_zig_version = "0.16.0",
    .dependencies = .{},
    .paths = .{ "build.zig", "build.zig.zon", "src" },
}
```

`zig fetch --save=zenai git+https://github.com/lightpanda-io/zenai`

```zig
const std = @import("std");
const zenai = @import("zenai");

fn onDelta(_: void, _: zenai.provider.GenerateResult) void {}

pub fn main(init: std.process.Init) !void {
    const client = try zenai.provider.Client.init(init.io, init.gpa, .openai, "key", .{});
    defer client.deinit(init.gpa);

    try client.generateContentStream(
        "gpt-4o",
        &.{.{ .role = .user, .content = "hi" }},
        .{},
        {},
        &onDelta,
    );
}
```

The result is:

```
src/provider.zig:759:41: error: expected type 'bool', found '?[]const provider.Tool'
                const tools = if (config.tools) mapAnthropicTools(req_alloc, config.tools.?) catch return error.OutOfMemory else null;
                                  ~~~~~~^~~~~~
referenced by:
    main: src/main.zig:10:37
```

`GenerationConfig.tools` is `?[]const Tool` (provider.zig:312), so the `if` needs a payload capture. The same mistake is on three lines, one per provider branch:

- provider.zig:696, Gemini
- provider.zig:721, OpenAI
- provider.zig:759, Anthropic

Every other site in the file has the correct form, including the three equivalent lines in `generateContent` at :576, :633 and :653:

```zig
const tools = if (config.tools) |t| try mapGeminiTools(req_alloc, t) else null;
```

**Comment by arrufat** [comment]
Thank you for the detailed report.
